### ISSUE TITLE
app crashes for guest_companoins < 0

### ISSUE THREAD

**Issue by arikgrahl** [RGreinacher/InvitationManager#1]
![bildschirmfoto am 2016-01-14 um 19 05 35](https://cloud.githubusercontent.com/assets/8049011/12332977/d0a9a920-baf1-11e5-8db6-98c34758c259.png)

**Comment by RGreinacher** [comment]
Thanks a lot! I had that tested - until the presents management was implemented ;) That's what made it crash. That's a pity because I really like the error notice... ;o)
